export const LEVELS: string[][] = [
  // Level 1: Introductory
  [
    "                                                                                              ",
    "                                                                                              ",
    "                                                                                              ",
    "                                                                                              ",
    "                                                                                              ",
    "                                                                                              ",
    "                                                                                              ",
    "                                                                                              ",
    "                                                                                              ",
    "                  ?   B?B                                                                     ",
    "                                                                                              ",
    "                                        ?  M  ?                                               ",
    "       S                  E                              E                           F        ",
    "              C     C          PPPP             C   C        C    E     C  C                   ",
    "GGGGGGGGGGGG  GGGGGGGGGGGGGGG  GGGGGGGGGGGGGGGGGGGGGGGG  GGGGGGGGGGGGGGGGGGGGG  GGGGGGGGGGGGG",
    "GGGGGGGGGGGG  GGGGGGGGGGGGGGG  GGGGGGGGGGGGGGGGGGGGGGGG  GGGGGGGGGGGGGGGGGGGGG  GGGGGGGGGGGGG",
  ],
  // Level 2: More enemies and power-ups
  [
    "                                                                                                            ",
    "                                                                                                            ",
    "                                                                                                            ",
    "                                                                                                            ",
    "                                                                                                            ",
    "                                                                                                            ",
    "                                                                                                            ",
    "                                    BBBBB                                                                   ",
    "                                                                   PPP                                      ",
    "                  ?M?                            ?  ?  ?                                                     ",
    "                                                                              PP                            ",
    "       S               E   E                E                E         E               E              F     ",
    "          C   C     C          PPP    C  C      PPPPP    C       C  C      C       C       C   C             ",
    "GGGGGGGGGGGGGGGGGG  GGGGGGGGGG  GGGGGGGGGGGGGGG  GGGGGGGGGGGGG  GGGGGGGGG  GGGGGGGGGGGGG  GGGGGGGGGGGGGGGGG",
    "GGGGGGGGGGGGGGGGGG  GGGGGGGGGG  GGGGGGGGGGGGGGG  GGGGGGGGGGGGG  GGGGGGGGG  GGGGGGGGGGGGG  GGGGGGGGGGGGGGGGG",
  ],
  // Level 3: Harder platforming
  [
    "                                                                                                                      ",
    "                                                                                                                      ",
    "                                                                                                                      ",
    "                                                                                                                      ",
    "                                                                                                                      ",
    "                                                                                           PPP                        ",
    "                                                               M                                                      ",
    "                           BBB                    PPP                  PPP                        PPP                  ",
    "                                        PPP                                    E                                       ",
    "              ?  ?                                       E                          PP                                 ",
    "                         E       E           E                    E                       E                    F       ",
    "       S    C     C   C     C       C   C       C   C      C  C     C     C   C      C      C   C    C  C             ",
    "GGGGGGGGG  GGGG  GGGGG  GGG  GGGG  GGGGG  GGGG  GGGG  GGGG  GGG  GGGG  GGGG  GGGG  GGGG  GGGG  GGG  GGGGGGGGGGGGG",
    "GGGGGGGGG  GGGG  GGGGG  GGG  GGGG  GGGGG  GGGG  GGGG  GGGG  GGG  GGGG  GGGG  GGGG  GGGG  GGGG  GGG  GGGGGGGGGGGGG",
  ],
];
