export const LEVELS: string[][] = [
  // Level 1: Introductory
  [
    "                                                                                              ",
    "                                                                                              ",
    "                                                                                              ",
    "                                                                                              ",
    "                                                                                              ",
    "                                                                                              ",
    "                                                                                              ",
    "                                                                                              ",
    "                                                                                              ",
    "                  ?   B?B                                                                     ",
    "                                                                                              ",
    "                                        ?  M  ?                                               ",
    "       S                  E                              E                           F        ",
    "              C     C          PPPP             C   C        C    E     C  C                   ",
    "GGGGGGGGGGGG  GGGGGGGGGGGGGGG  GGGGGGGGGGGGGGGGGGGGGGGG  GGGGGGGGGGGGGGGGGGGGG  GGGGGGGGGGGGG",
    "GGGGGGGGGGGG  GGGGGGGGGGGGGGG  GGGGGGGGGGGGGGGGGGGGGGGG  GGGGGGGGGGGGGGGGGGGGG  GGGGGGGGGGGGG",
  ],
  // Level 2: More enemies and power-ups
  [
    "                                                                                                            ",
    "                                                                                                            ",
    "                                                                                                            ",
    "                                                                                                            ",
    "                                                                                                            ",
    "                                                                                                            ",
    "                                                                                                            ",
    "                                    BBBBB                                                                   ",
    "                                                                   PPP                                      ",
    "                  ?M?                            ?  ?  ?                                                     ",
    "                                                                              PP                            ",
    "       S               E   E                E                E         E               E              F     ",
    "          C   C     C          PPP    C  C      PPPPP    C       C  C      C       C       C   C             ",
    "GGGGGGGGGGGGGGGGGG  GGGGGGGGGG  GGGGGGGGGGGGGGG  GGGGGGGGGGGGG  GGGGGGGGG  GGGGGGGGGGGGG  GGGGGGGGGGGGGGGGG",
    "GGGGGGGGGGGGGGGGGG  GGGGGGGGGG  GGGGGGGGGGGGGGG  GGGGGGGGGGGGG  GGGGGGGGG  GGGGGGGGGGGGG  GGGGGGGGGGGGGGGGG",
  ],
  // Level 3: Harder platforming
  [
    "                                                                                                                      ",
    "                                                                                                                      ",
    "                                                                                                                      ",
    "                                                                                                                      ",
    "                                                                                                                      ",
    "                                                                                           PPP                        ",
    "                                                               M                                                      ",
    "                           BBB                    PPP                  PPP                        PPP                  ",
    "                                        PPP                                    E                                       ",
    "              ?  ?                                       E                          PP                                 ",
    "                         E       E           E                    E                       E                    F       ",
    "       S    C     C   C     C       C   C       C   C      C  C     C     C   C      C      C   C    C  C             ",
    "GGGGGGGGG  GGGG  GGGGG  GGG  GGGG  GGGGG  GGGG  GGGG  GGGG  GGG  GGGG  GGGG  GGGG  GGGG  GGGG  GGG  GGGGGGGGGGGGG",
    "GGGGGGGGG  GGGG  GGGGG  GGG  GGGG  GGGGG  GGGG  GGGG  GGGG  GGG  GGGG  GGGG  GGGG  GGGG  GGGG  GGG  GGGGGGGGGGGGG",
  ],
  // Level 4: Underground — dense bricks, lots of Goombas
  [
    "                                                                                                    ",
    "                                                                                                    ",
    "  BBBBBBBBB           BBBBBBBBB           BBBBBBBBB           BBBBBBBBB           BBBBBBBBB         ",
    "                                                                                                    ",
    "  B?B?B?B             B?B?B?B             B?B?B?B             B?B?B?B             B?B?B?B           ",
    "                                                                                                    ",
    "  BBBBBBBBB           BBBBBBBBB           BBBBBBBBB           BBBBBBBBB           BBBBBBBBB         ",
    "                                                                                                    ",
    "                                                                                                    ",
    "                                                                                                    ",
    "                                                                                                    ",
    "    S      E    E          E    E    E         E    E    E          E    E    K            F         ",
    "              C    C  C        C C      C  C        C C     C  C        C C      C  C               ",
    "GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG",
    "GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG",
    "GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG",
  ],
  // Level 5: Sky — mostly platforms, Paratroopas, wide gaps
  [
    "                                                                                                    ",
    "                                                                                                    ",
    "                PPP                    PPP                    PPPP                   PPP            ",
    "                                                                                                    ",
    "         PPP          W       PPPP           W        PPP           W       PPPP                   ",
    "                                                                                                    ",
    "    PPP        W                   PPP              PPP        W                   PPP              ",
    "                                                                                                    ",
    "                  PPPP    W               PPPP   W                  PPPP                    W       ",
    "                                                                                                    ",
    "                                                                                                    ",
    "  S                C   C        C    C         C    C       C    C        C    C      C         F   ",
    "GGGGGG             GGGGGGGGGG   GGGGGGGGGG     GGGGGGGGGG   GGGGGGGGGG   GGGGGGGGGG  GGGGGGGGGGGGGG",
    "GGGGGG             GGGGGGGGGG   GGGGGGGGGG     GGGGGGGGGG   GGGGGGGGGG   GGGGGGGGGG  GGGGGGGGGGGGGG",
    "GGGGGG                                                                               GGGGGGGGGGGGGG",
    "GGGGGG                                                                               GGGGGGGGGGGGGG",
  ],
  // Level 6: Speed Run — wide open, lots of coins, tight timer
  [
    "                                                                                                              ",
    "                                                                                                              ",
    "                                                                                                              ",
    "                                                                                                              ",
    "                                                                                                              ",
    "          ?  ?  ?  ?  ?                    ?  ?  ?  ?  ?                    ?  ?  ?  ?  ?                    ",
    "                                                                                                              ",
    "                C  C  C  C  C                             C  C  C  C  C                          C  C  C      ",
    "                                                                                                              ",
    "                                                                                                              ",
    "                                                                                                              ",
    "    S        E           E        E           E        E           E        E           E              F       ",
    "           PPPPPP      PPPPPP   PPPPPP      PPPPPP  PPPPPP      PPPPPP   PPPPPP      PPPPPP               ",
    "GGGGGGGGG                                                                                     GGGGGGGGGGGGGGG",
    "GGGGGGGGG                                                                                     GGGGGGGGGGGGGGG",
    "GGGGGGGGG                                                                                     GGGGGGGGGGGGGGG",
  ],
  // Level 7: Boss Gauntlet — dense enemies, many ? boxes, tricky jumps
  [
    "                                                                                                    ",
    "                                                                                                    ",
    "                                                                                                    ",
    "        ?M??M??M?            ?M??M??M?            ?M??M??M?            ?M??M??M?                   ",
    "                                                                                                    ",
    "    BBBBBBBBB     PPP    BBBBBBBBB     PPP    BBBBBBBBB     PPP    BBBBBBBBB     PPP                ",
    "                                                                                                    ",
    "                     ?  ?  ?  ?                      ?  ?  ?  ?                                    ",
    "                                                                                                    ",
    "                                                                                                    ",
    "                                                                                                    ",
    "  S    E  E  K    E     W   E  E  K    E     W   E  E  K    E     W   E  E  K    E     W       F   ",
    "        C     C      C       C     C      C       C     C      C       C     C      C               ",
    "GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG",
    "GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG",
    "GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG",
  ],
  // Level 8: Final Challenge — all elements, hardest layout
  [
    "                                                                                                                  ",
    "                                                                                                                  ",
    "                                          PPP                       PPP                                           ",
    "           BBBBB                W                   W                        BBBBB          W                     ",
    "                                                                                                                  ",
    "     ?M?         PPP    ?M?           PPP    ?M?          PPP    ?M?                PPP    ?M?                    ",
    "                                                                                                                  ",
    "  BBBBBBBBB                  BBBBBBBBB                BBBBBBBBB                BBBBBBBBB                         ",
    "                                                                                                                  ",
    "                    W                      W                      W                      W                        ",
    "                                                                                                                  ",
    "  S   E  K  E  W  E  E  K  E  W  E  E  K  E  W  E  E  K  E  W  E  E  K  E  W  E  E  K  E  W  E  E  K  E  F    ",
    "        C    C      C    C      C    C      C    C      C    C      C    C      C    C      C    C               ",
    "GGGGGGG  GGGGGGGGG  GGGGGGGGG  GGGGGGGGG  GGGGGGGGG  GGGGGGGGG  GGGGGGGGG  GGGGGGGGG  GGGGG  GGGGGGGGGGGGGGGGGG",
    "GGGGGGG  GGGGGGGGG  GGGGGGGGG  GGGGGGGGG  GGGGGGGGG  GGGGGGGGG  GGGGGGGGG  GGGGGGGGG  GGGGG  GGGGGGGGGGGGGGGGGG",
    "GGGGGGG  GGGGGGGGG  GGGGGGGGG  GGGGGGGGG  GGGGGGGGG  GGGGGGGGG  GGGGGGGGG  GGGGGGGGG  GGGGG  GGGGGGGGGGGGGGGGGG",
  ],
];
